[package]
name = "azurite-common"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
hmac.workspace = true
jsonwebtoken.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
tokio.workspace = true
tokio-test.workspace = true
tower.workspace = true
